version: '3.3'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password --init-file="/tmp/database/abarrotes.sql"
    volumes:
      - ./abarrotes.sql:/tmp/database/abarrotes.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: abarrotes
      MYSQL_USER: rnfu
      MYSQL_PASSWORD: qwer1234
    ports:
      - 3306:3306

  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    depends_on: 
      - mysql_db
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: "npm start"